name: Metrics
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip
        pip3 install codecov

    - name: Run tests and generate code coverage report
      run: |
        # Run tests
        # Generate code coverage report
        codecov --token=YOUR_TOKEN

      env:
        CI: true
